Added Camera Clamping
itcgames/ARGO_2018_19_A pull request #11
Opened 2019-02-11 12:46 UTC by JohnCodd

2019-02-11 12:54 UTC, rafael-plugge requested changes
There is one change + one thing missing.

Change:
``` cpp
math::Vector2f clampTopLeft;
math::Vector2f clampSize;
bool clamp = false;
```
would recommend changing to
``` cpp
std::optional<math::Rectf> clamp;
```

and its missing the inner rectangle give away (there is a small rectangle that if the player is inside it, the camera doesn't follow it).

2019-02-11 15:45 UTC, JohnCodd commented
Changes have been made

2019-02-11 17:24 UTC, rafael-plugge requested changes

2019-02-11 17:24 UTC, rafael-plugge commented on ArgoProject/src/parameters/CameraParameters.h
> +		std::optional<bool> clamp = false;
member variable not used

2019-02-11 17:24 UTC, rafael-plugge commented on ArgoProject/src/components/Camera.h
> +		std::optional<float> internalClampSize;
```suggestion
		std::optional<math::Vector2f> internalClamp;
```
Needs to have different values for x-axis vs y-axis.

2019-02-11 17:24 UTC, rafael-plugge commented on ArgoProject/src/factories/scenes/LevelSceneFactory.cpp
> +	entities.push_back(fact::CameraFactory(app::par::CameraParameters{ player, math::Rectf(app::math::Vector2f(-800, 500), app::math::Vector2f(2000, 1000)), true, 20 }).create());
```suggestion
	auto cameraParams = app::par::CameraParameters();
	cameraParams.targetEntity = player;
	cameraParams.clampRect = math::Rectf({ -800.0f, 500.0f }, { 2000.0f, 1000.0f});
	cameraParams.internalClamp = math::Vector2f(20.0f, 60.0f); // for when this gets changed
	entities.push_back(fact::CameraFactory(std::move(cameraParams)).create());
```
makes it more readable.

2019-02-11 17:24 UTC, rafael-plugge commented on ArgoProject/src/parameters/CameraParameters.h
> +		std::optional<float> internalClampSize;
```suggestion
		std::optional<math::Vector2f> internalClamp;
```
internal clamp needs varying x-axis and y-axis values.

2019-02-11 17:24 UTC, rafael-plugge commented on ArgoProject/src/systems/CameraSystem.cpp
> +				math::Vector2f clampPosition = camera.center;
Not needed, apply changes to `camera.center` directly.

2019-02-11 17:24 UTC, rafael-plugge commented on ArgoProject/src/systems/CameraSystem.cpp
> +				bool followPlayer = false;
no need fi changes applied directly

2019-02-11 17:24 UTC, rafael-plugge commented on ArgoProject/src/systems/CameraSystem.cpp
> +			//camera.position = targetLocation.position - (camera.size / 2.0f);
Unneeded comment

2019-02-12 10:52 UTC, rafael-plugge requested changes

2019-02-12 10:52 UTC, rafael-plugge commented on ArgoProject/src/systems/CameraSystem.cpp
> +			math::Vector2f targetPosition = targetLocation.position;
```suggestion
			math::Vector2f const & targetPosition = targetLocation.position;
```
this way the compiler can optimise away the `targetPosition`

2019-02-12 11:08 UTC, rafael-plugge approved these changes
:+1:

2019-02-12 11:10 UTC, merged